export const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST";
export const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS";
export const ALL_ORDERS_FAIL = "ALL_ORDERS_FAIL"; 

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL"; 

export const GET_MY_ORDERS_REQUEST = "GET_MY_ORDERS_REQUEST";
export const GET_MY_ORDERS_SUCCESS = "GET_MY_ORDERS_SUCCESS";
export const GET_MY_ORDERS_FAIL = "GET_MY_ORDERS_FAIL"; 

export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL"; 
export const UPDATE_ORDER_RESET = "UPDATE_ORDER_RESET";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL"; 
export const DELETE_ORDER_RESET = "DELETE_ORDER_RESET";

export const NEW_ORDER_REQUEST = "NEW_ORDER_REQUEST";
export const NEW_ORDER_SUCCESS = "NEW_ORDER_SUCCESS";
export const NEW_ORDER_FAIL = "NEW_ORDER_FAIL"; 
export const NEW_ORDER_RESET = "NEW_ORDER_RESET";

export const GET_BY_STATUS_ORDERS_REQUEST = "GET_BY_STATUS_ORDERS_REQUEST";
export const GET_BY_STATUS_ORDERS_SUCCESS = "GET_BY_STATUS_ORDERS_SUCCESS";
export const GET_BY_STATUS_ORDERS_FAIL = "GET_BY_STATUS_ORDERS_FAIL"; 

export const GET_MONTHLY_ORDERS_REQUEST = "GET_MONTHLY_ORDERS_REQUEST";
export const GET_MONTHLY_ORDERS_SUCCESS = "GET_MONTHLY_ORDERS_SUCCESS";
export const GET_MONTHLY_ORDERS_FAIL = "GET_MONTHLY_ORDERS_FAIL"; 

export const GET_WEEKLY_ORDERS_REQUEST = "GET_WEEKLY_ORDERS_REQUEST";
export const GET_WEEKLY_ORDERS_SUCCESS = "GET_WEEKLY_ORDERS_SUCCESS";
export const GET_WEEKLY_ORDERS_FAIL = "GET_WEEKLY_ORDERS_FAIL"; 

export const GET_TODAY_ORDERS_REQUEST = "GET_TODAY_ORDERS_REQUEST";
export const GET_TODAY_ORDERS_SUCCESS = "GET_TODAY_ORDERS_SUCCESS";
export const GET_TODAY_ORDERS_FAIL = "GET_TODAY_ORDERS_FAIL"; 

export const TO_UPDATE_ORDER = "TO_UPDATE_ORDER";
export const ADD_TO_UPDATE_ORDER = "ADD_TO_UPDATE_ORDER";
export const REMOVE_ORDER_ITEM = "REMOVE_ORDER_ITEM";

export const CLEAR_ERRORS = 'CLEAR_ERRORS'